url: http://hazirguo.github.io/demo
baseurl: /demo/blog
#markdown: rdiscount
#permalink: /blog/:year:month:day
pygments: /blog/:year:month:day/:title.html
exclude: ['Rakefile.rb', 'CNAME', 'README.markdown']
